# Generated by Django 6.0.6 on 2026-06-05 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaOperasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('kategori', models.CharField(choices=[('listrik', 'Listrik'), ('air', 'Air'), ('nutrisi', 'Nutrisi'), ('media_tanam', 'Media Tanam'), ('peralatan', 'Peralatan'), ('tenaga_kerja', 'Tenaga Kerja'), ('transportasi', 'Transportasi'), ('pemeliharaan', 'Pemeliharaan'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Kategori')),
                ('deskripsi', models.CharField(max_length=200, verbose_name='Deskripsi')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah (Rp)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Biaya Operasional',
                'verbose_name_plural': 'Data Biaya Operasional',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Bibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Bibit')),
                ('jenis', models.CharField(choices=[('sayuran_daun', 'Sayuran Daun'), ('sayuran_buah', 'Sayuran Buah'), ('herbal', 'Herbal'), ('buah', 'Buah'), ('bunga', 'Bunga')], max_length=20, verbose_name='Jenis Tanaman')),
                ('varietas', models.CharField(blank=True, max_length=100, verbose_name='Varietas')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Supplier')),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Beli (Rp)')),
                ('stok', models.PositiveIntegerField(default=0, verbose_name='Stok (unit)')),
                ('tanggal_masuk', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Masuk')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Bibit',
                'verbose_name_plural': 'Data Bibit',
                'ordering': ['-tanggal_masuk', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Penanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tanam', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Tanam')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah Tanam')),
                ('lokasi', models.CharField(max_length=100, verbose_name='Lokasi / Rak')),
                ('sistem_hidroponik', models.CharField(choices=[('nft', 'NFT (Nutrient Film Technique)'), ('dft', 'DFT (Deep Flow Technique)'), ('wick', 'Wick System'), ('drip', 'Drip System'), ('ebb_flow', 'Ebb & Flow'), ('aeroponik', 'Aeroponik')], max_length=20, verbose_name='Sistem Hidroponik')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('masa_tumbuh', 'Masa Tumbuh'), ('siap_panen', 'Siap Panen'), ('selesai', 'Selesai'), ('gagal', 'Gagal')], default='aktif', max_length=20, verbose_name='Status')),
                ('estimasi_panen', models.DateField(blank=True, null=True, verbose_name='Estimasi Panen')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('bibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penanaman', to='farm.bibit', verbose_name='Bibit')),
            ],
            options={
                'verbose_name': 'Penanaman',
                'verbose_name_plural': 'Data Penanaman',
                'ordering': ['-tanggal_tanam'],
            },
        ),
        migrations.CreateModel(
            name='Pemanenan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_panen', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Panen')),
                ('jumlah_panen', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah Panen')),
                ('satuan', models.CharField(choices=[('kg', 'Kilogram'), ('gram', 'Gram'), ('ikat', 'Ikat'), ('buah', 'Buah'), ('liter', 'Liter'), ('lusin', 'Lusin')], default='kg', max_length=10, verbose_name='Satuan')),
                ('kualitas', models.CharField(choices=[('premium', 'Premium'), ('baik', 'Baik'), ('cukup', 'Cukup')], default='baik', max_length=10, verbose_name='Kualitas')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('penanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemanenan', to='farm.penanaman', verbose_name='Penanaman')),
            ],
            options={
                'verbose_name': 'Pemanenan',
                'verbose_name_plural': 'Data Pemanenan',
                'ordering': ['-tanggal_panen'],
            },
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_jual', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Jual')),
                ('pembeli', models.CharField(max_length=200, verbose_name='Nama Pembeli')),
                ('jumlah_jual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah Jual')),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan (Rp)')),
                ('status_pembayaran', models.CharField(choices=[('lunas', 'Lunas'), ('belum_bayar', 'Belum Bayar'), ('cicilan', 'Cicilan')], default='lunas', max_length=15, verbose_name='Status Pembayaran')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('pemanenan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjualan', to='farm.pemanenan', verbose_name='Pemanenan')),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Data Penjualan',
                'ordering': ['-tanggal_jual'],
            },
        ),
        migrations.CreateModel(
            name='Perawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Perawatan')),
                ('jenis_perawatan', models.CharField(choices=[('pemupukan', 'Pemupukan'), ('pengaturan_ph', 'Pengaturan pH'), ('penggantian_air', 'Penggantian Air'), ('pengendalian_hama', 'Pengendalian Hama'), ('pemangkasan', 'Pemangkasan'), ('pembersihan', 'Pembersihan Sistem'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Jenis Perawatan')),
                ('nutrisi_digunakan', models.CharField(blank=True, max_length=200, verbose_name='Nutrisi Digunakan')),
                ('ph_air', models.FloatField(blank=True, null=True, verbose_name='pH Air')),
                ('ec', models.FloatField(blank=True, null=True, verbose_name='EC (mS/cm)')),
                ('volume_nutrisi_ml', models.FloatField(blank=True, null=True, verbose_name='Volume Nutrisi (ml)')),
                ('biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya (Rp)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('penanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perawatan', to='farm.penanaman', verbose_name='Penanaman')),
            ],
            options={
                'verbose_name': 'Perawatan',
                'verbose_name_plural': 'Data Perawatan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
